services:
  db:
    image: postgres:15
    container_name: go_balance_manager_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"  # Host:Container
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go_balance_manager_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      APP_ADDR: "${APP_ADDR}"
      SEED: "false" # Set to "true" to seed data on startup
    ports:
      - "8081:8080"  # Host:Container
    volumes:
      - ./bin:/app/bin

volumes:
  db_data: